[package]
name = "kermit"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4", features = ["env"] }
reqwest = { version = "0.12.12", features = ["json"] }
serde = "1.0.217"
