condense_wildcard_suffixes = true
edition = "2021"
style_edition = "2021"
max_width = 100
error_on_line_overflow = true
error_on_unformatted = true
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
match_block_trailing_comma = true
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
use_field_init_shorthand = true
wrap_comments = true
