use anyhow::{Context, Result};
use clap::{Args, Parser, ValueEnum};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use strum::Display;

use crate::{
    account::signature::{GLSecp256k1PrivateKey, PrivateKey},
    config::config::{Config, Network},
    contracts_funcs::{
        compile::compile,
        compile_project::{
            compile_project::{FieldsTypesMapMut, FieldsVec, load_compile_project},
            compile_project_values::config_fields_to_vec,
        },
        deploy::deploy_contract,
        state::state,
        test::test_contract,
    },
};

#[derive(Clone, Debug, Display, ValueEnum)]
pub enum CompiledType {
    Contract,
    Script,
}

#[derive(Clone, Copy, Debug, Display, ValueEnum, PartialEq, Eq)]
pub enum NetworkType {
    Main = 0,
    Test = 1,
    Dev = 4,
}

#[derive(Debug, Clone, Args, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CompilerOptions {
    #[arg(
        long,
        default_value_t = false,
        help = "Ignore external caller warnings"
    )]
    pub ignore_check_external_caller_warnings: bool,

    #[arg(
        long,
        default_value_t = false,
        help = "Ignore unused constants warnings"
    )]
    pub ignore_unused_constants_warnings: bool,

    #[arg(long, default_value_t = false, help = "Ignore unused fields warnings")]
    pub ignore_unused_fields_warnings: bool,

    #[arg(
        long,
        default_value_t = false,
        help = "Ignore unused function return warnings"
    )]
    pub ignore_unused_function_return_warnings: bool,

    #[arg(
        long,
        default_value_t = false,
        help = "Ignore unused private functions warnings"
    )]
    pub ignore_unused_private_functions_warnings: bool,

    #[arg(
        long,
        default_value_t = false,
        help = "Ignore unused variables warnings"
    )]
    pub ignore_unused_variables_warnings: bool,

    #[arg(
        long,
        default_value_t = false,
        help = "Ignore update fields check warnings"
    )]
    pub ignore_update_fields_check_warnings: bool,

    #[arg(long, default_value_t = false, help = "Skip abstract contract check")]
    pub skip_abstract_contract_check: bool,

    #[arg(long, default_value_t = false, help = "Skip tests")]
    pub skip_tests: bool,
}

fn parse_key_val(s: &str) -> anyhow::Result<(String, String), String> {
    let parts: Vec<&str> = s.splitn(2, '=').collect();
    if parts.len() != 2 {
        return Err(format!("Invalid KEY=VALUE: '{}'", s));
    }
    Ok((parts[0].to_string(), parts[1].to_string()))
}

#[derive(Parser)]
pub enum ContractsSubcommands {
    #[command(visible_alias = "c")]
    Compile {
        file_path: String,
        #[command(flatten)]
        compiler_options: CompilerOptions,
        #[arg(
            long,
            help = "skip generate typescript code by contract artifacts",
            default_value_t = false
        )]
        skip_generate: bool,
        #[arg(
            long,
            help = "show detailed debug information such as error stack traces",
            default_value_t = false
        )]
        debug: bool,
        #[arg(long, help = "enable force recompile", default_value_t = false)]
        force: bool,
    },
    #[command(visible_alias = "d")]
    Deploy {
        #[arg(long, default_value_t = CompiledType::Contract)]
        compiled_type: CompiledType,
        contract_name: String,
        compile_output_path: String,
        #[arg(long, value_name = "config", help = "Path to the .project.json generated by last compilation", default_value_t=String::from("./.project.json"))]
        project_path: String,
        #[arg(long, env)]
        private_key: Option<String>,
    },
    #[command(visible_alias = "s")]
    State { contract_id: String },
    #[command(visible_alias = "t")]
    Test {
        contract_name: String,
        contract_id: String,
        compile_output_path: String,
        method_name: String,
        #[arg(long = "args", value_parser = parse_key_val, num_args = 1..)]
        args: Vec<(String, String)>,
        #[arg(long = "existing-contracts", value_name = "CONTRACT_ID", num_args = 0.., help = "List of existing contracts to include in the test")]
        exiting_contracts: Vec<String>,
        #[arg(long, env)]
        private_key: Option<String>,
    },
}

fn get_contract_initial_fields(
    config: &Config,
    contract_name: &str,
    contract_fields_types: &FieldsTypesMapMut,
) -> Result<FieldsVec> {
    let contracts_map = config
        .contracts
        .to_owned()
        .context("No 'contracts' field in config")?;
    let config_contract = contracts_map
        .get(contract_name)
        .context(format!("Contract '{}' not found in config", contract_name))?
        .to_owned();

    config_fields_to_vec(config_contract.initial_fields, contract_fields_types)
}

fn load_private_key(pk_path: &Option<String>, network: &Network) -> Result<Box<dyn PrivateKey>> {
    let private_key = if let Some(path) = pk_path {
        let private_key: Box<dyn PrivateKey> = Box::new(GLSecp256k1PrivateKey::new(&path)?);
        Some(private_key)
    } else {
        None
    };

    let private_key = if let Some(private_key) = private_key {
        private_key
    } else {
        let private_keys = network
            .private_keys
            .as_ref()
            .context("No private keys found in devnet configuration")?;

        let private_key = private_keys
            .get(0)
            .context("No private keys found in devnet configuration")?;

        Box::new(GLSecp256k1PrivateKey::new(private_key)?)
    };

    Ok(private_key)
}

impl ContractsSubcommands {
    pub async fn run(
        self,
        url: &str,
        config: &Config,
        network: &Network,
        network_id: NetworkType,
    ) -> Result<()> {
        let value: Value = match self {
            Self::Compile {
                file_path,
                compiler_options,
                skip_generate,
                debug,
                force,
            } => {
                compile(
                    url,
                    &file_path,
                    network,
                    config,
                    compiler_options,
                    skip_generate,
                    debug,
                    force,
                )
                .await?
            },
            Self::Deploy {
                compiled_type,
                contract_name,
                compile_output_path,
                project_path,
                private_key,
            } => {
                let compiled_project = load_compile_project(&compile_output_path)?;

                match compiled_type {
                    CompiledType::Contract => {
                        let contract = compiled_project.get_contract_by_name(&contract_name)?;

                        let initial_fields = get_contract_initial_fields(
                            config,
                            &contract_name,
                            &contract.fields_types,
                        )?;

                        let private_key = load_private_key(&private_key, network)?;

                        deploy_contract(
                            url,
                            private_key,
                            network,
                            network_id,
                            &contract,
                            initial_fields,
                        )
                        .await?
                    },
                    CompiledType::Script => {
                        unimplemented!("Script deployment is not implemented yet");
                    },
                }
            },
            Self::State { contract_id } => state(url, &contract_id).await?,
            Self::Test {
                method_name,
                contract_name,
                contract_id,
                compile_output_path,
                private_key,
                args,
                exiting_contracts,
            } => {
                let compiled_project = load_compile_project(&compile_output_path)?;
                let contract = compiled_project.get_contract_by_name(&contract_name)?;

                let contracts_map = config
                    .contracts
                    .to_owned()
                    .context("No 'contracts' field in config")?;
                let config_contract = contracts_map
                    .get(&contract.name)
                    .context(format!("Contract '{}' not found in config", contract_name))?
                    .to_owned();

                let initial_fields =
                    config_fields_to_vec(config_contract.initial_fields, &contract.fields_types)?;

                let exiting_contracts = exiting_contracts
                    .iter()
                    .map(|id| id.as_str())
                    .collect::<Vec<_>>();

                test_contract(
                    url,
                    &method_name,
                    &contract_id,
                    contract,
                    initial_fields,
                    &config_contract.initial_asset,
                    &config_contract.input_assets,
                    args,
                    exiting_contracts,
                )
                .await?
            },
        };

        serde_json::to_writer_pretty(std::io::stdout(), &value)?;
        println!();
        Ok(())
    }
}
