use anyhow::{Context, Result, anyhow};
use clap::{Args, Parser, ValueEnum};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use strum::Display;

use crate::{
    account::signature::{GLSecp256k1PrivateKey, PrivateKey}, contracts_funcs::{
        compile::compile, compile_project::compile_project::{fields_vec_to_fields_map, load_compile_project, FieldsTypesMap}, config::Config, deploy::deploy_contract, project::Project, state::state, test::test_contract
    }, network::health::is_network_alive, utils::fs::read_file
};

#[derive(Clone, Debug, Display, ValueEnum)]
pub enum CompiledType {
    Contract,
    Script,
}

#[derive(Clone, Copy, Debug, Display, ValueEnum, PartialEq, Eq)]
pub enum NetworkType {
    Main = 0,
    Test = 1,
    Dev = 4,
}

#[derive(Debug, Clone, Args, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CompilerOptions {
    #[arg(
        long,
        default_value_t = false,
        help = "Ignore external caller warnings"
    )]
    pub ignore_check_external_caller_warnings: bool,

    #[arg(
        long,
        default_value_t = false,
        help = "Ignore unused constants warnings"
    )]
    pub ignore_unused_constants_warnings: bool,

    #[arg(long, default_value_t = false, help = "Ignore unused fields warnings")]
    pub ignore_unused_fields_warnings: bool,

    #[arg(
        long,
        default_value_t = false,
        help = "Ignore unused function return warnings"
    )]
    pub ignore_unused_function_return_warnings: bool,

    #[arg(
        long,
        default_value_t = false,
        help = "Ignore unused private functions warnings"
    )]
    pub ignore_unused_private_functions_warnings: bool,

    #[arg(
        long,
        default_value_t = false,
        help = "Ignore unused variables warnings"
    )]
    pub ignore_unused_variables_warnings: bool,

    #[arg(
        long,
        default_value_t = false,
        help = "Ignore update fields check warnings"
    )]
    pub ignore_update_fields_check_warnings: bool,

    #[arg(long, default_value_t = false, help = "Skip abstract contract check")]
    pub skip_abstract_contract_check: bool,

    #[arg(long, default_value_t = false, help = "Skip tests")]
    pub skip_tests: bool,
}

fn parse_key_val(s: &str) -> anyhow::Result<(String, String), String> {
    let parts: Vec<&str> = s.splitn(2, '=').collect();
    if parts.len() != 2 {
        return Err(format!("Invalid KEY=VALUE: '{}'", s));
    }
    Ok((parts[0].to_string(), parts[1].to_string()))
}

#[derive(Parser)]
pub enum ContractsSubcommands {
    #[command(visible_alias = "c")]
    Compile {
        file_path: String,
        #[arg(long, default_value_t = NetworkType::Main)]
        network: NetworkType,
        #[arg(long, value_name = "config", help = "Path to the config YAML file", default_value_t=String::from("./alephium.config.yaml"))]
        config_path: String,
        #[command(flatten)]
        compiler_options: CompilerOptions,
        #[arg(
            long,
            help = "skip generate typescript code by contract artifacts",
            default_value_t = false
        )]
        skip_generate: bool,
        #[arg(
            long,
            help = "show detailed debug information such as error stack traces",
            default_value_t = false
        )]
        debug: bool,
        #[arg(long, help = "enable force recompile", default_value_t = false)]
        force: bool,
    },
    #[command(visible_alias = "d")]
    Deploy {
        #[arg(long, default_value_t = NetworkType::Main)]
        network: NetworkType,
        #[arg(long, default_value_t = CompiledType::Contract)]
        compiled_type: CompiledType,
        #[arg(help = "Index in the list of the wanted compiled object")]
        compiled_index: usize,
        compile_output_path: String,
        #[arg(long, value_name = "config", help = "Path to the .project.json generated by last compilation", default_value_t=String::from("./.project.json"))]
        project_path: String,
        #[arg(long, value_name = "config", help = "Path to the config YAML file", default_value_t=String::from("./alephium.config.yaml"))]
        config_file_path: String,
        #[arg(long, env)]
        private_key: Option<String>,
        #[arg(long = "initial-fields", value_parser = parse_key_val, 
             num_args = 1.., 
            help = "Initial fields in the format KEY=VALUE, e.g. --initial-fields field1=value1 field2=value2")]
        initial_fields: Vec<(String, String)>,
    },
    #[command(visible_alias = "s")]
    State {
        #[arg(long, value_name = "config", help = "Path to the config YAML file", default_value_t=String::from("./alephium.config.yaml"))]
        config_file_path: String,
        #[arg(long, default_value_t = NetworkType::Main)]
        network: NetworkType,
        contract_id: String,
    },
    #[command(visible_alias = "t")]
    Test {
        #[arg(long, value_name = "config", help = "Path to the config YAML file", default_value_t=String::from("./alephium.config.yaml"))]
        config_file_path: String,
        #[arg(long, default_value_t = NetworkType::Main)]
        network: NetworkType,
        method_name: String,
        contract_id: String
    }
}

impl ContractsSubcommands {
    pub async fn run(self, url: &str) -> Result<()> {
        let value: Value = match self {
            Self::Compile {
                file_path,
                network,
                config_path,
                compiler_options,
                skip_generate,
                debug,
                force,
            } => {
                compile(
                    url,
                    &file_path,
                    network,
                    &config_path,
                    compiler_options,
                    skip_generate,
                    debug,
                    force,
                )
                .await?
            },
            Self::Deploy {
                network,
                compiled_type,
                compiled_index,
                compile_output_path,
                project_path,
                config_file_path: config_path,
                private_key,
                initial_fields,
            } => {
                let project = Project::try_from(read_file(&project_path)?.as_str())?;
                let compiled_project = load_compile_project(&compile_output_path)?;

                match compiled_type {
                    CompiledType::Contract => {
                        let config = Config::new(&config_path)?;
                        let contract = compiled_project
                            .contracts
                            .get(compiled_index)
                            .context("Invalid compiled index")?;

                        let fields_map = contract.fields_types
                            .iter()
                            .map(|(name, (type_name, _))| (name.clone(), type_name.clone()))
                            .collect::<FieldsTypesMap>();
                        let initial_fields = fields_vec_to_fields_map(initial_fields, &fields_map)?;

                        let private_key = if let Some(path) = private_key {
                            let private_key: Box<dyn PrivateKey> =
                                Box::new(GLSecp256k1PrivateKey::new(&path)?);
                            Some(private_key)
                        } else {
                            None
                        };

                        deploy_contract(
                            url,
                            private_key,
                            network,
                            config,
                            &contract,
                            initial_fields,
                        )
                        .await?
                    },
                    CompiledType::Script => {
                        unimplemented!("Script deployment is not implemented yet");
                    },
                }
            },
            Self::State { network, contract_id, config_file_path } => {
                let config = Config::new(&config_file_path)?;

                let network = match &network {
                    NetworkType::Dev => &config.configuration.networks.devnet,
                    NetworkType::Test => &config.configuration.networks.testnet,
                    NetworkType::Main => &config.configuration.networks.mainnet,
                };

                if !is_network_alive(&network.node_url).await? {
                    return Err(anyhow!("Network is not reachable: {}", network.node_url));
                }

                state(
                    url,
                    &contract_id,
                )
                .await?
            },
            Self::Test { config_file_path, network, method_name, contract_id } => {
                let config = Config::new(&config_file_path)?;

                let network = match &network {
                    NetworkType::Dev => &config.configuration.networks.devnet,
                    NetworkType::Test => &config.configuration.networks.testnet,
                    NetworkType::Main => &config.configuration.networks.mainnet,
                };

                if !is_network_alive(&network.node_url).await? {
                    return Err(anyhow!("Network is not reachable: {}", network.node_url));
                }

                test_contract(
                    url,
                    &config,
                    &method_name,
                    &contract_id,
                    vec![]
                ).await?
            }
        };

        serde_json::to_writer_pretty(std::io::stdout(), &value)?;
        println!();
        Ok(())
    }
}
